//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIDEO_CLUB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VIDEOEntities1 : DbContext
    {
        public VIDEOEntities1()
            : base("name=VIDEOEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACTOR> ACTOR { get; set; }
        public virtual DbSet<ACTOR_PELICULA> ACTOR_PELICULA { get; set; }
        public virtual DbSet<ALQUILER> ALQUILER { get; set; }
        public virtual DbSet<DIRECTOR> DIRECTOR { get; set; }
        public virtual DbSet<FORMATO> FORMATO { get; set; }
        public virtual DbSet<GENERO> GENERO { get; set; }
        public virtual DbSet<PELICULA> PELICULA { get; set; }
        public virtual DbSet<SEXO> SEXO { get; set; }
        public virtual DbSet<SOCIO> SOCIO { get; set; }
    }
}
