//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecuaciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ecuacion
    {
        public ecuacion()
        {
            this.evaluacion = new HashSet<evaluacion>();
        }
    
        public int idecuacion { get; set; }
        public int a { get; set; }
        public int b { get; set; }
        public int c { get; set; }
    
        public virtual ICollection<evaluacion> evaluacion { get; set; }
    }
}
