//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecuaciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class evaluacion
    {
        public int idevaluacion { get; set; }
        public Nullable<int> valor { get; set; }
        public int ecuacion_idecuacion { get; set; }
    
        public virtual ecuacion ecuacion { get; set; }
    }
}
