//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ejercicio_Prueba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ciudad
    {
        public ciudad()
        {
            this.parroquia = new HashSet<parroquia>();
        }
    
        public int idciudad { get; set; }
        public string ciu_nombre { get; set; }
        public int provincia_idprovincia { get; set; }
    
        public virtual provincia provincia { get; set; }
        public virtual ICollection<parroquia> parroquia { get; set; }
    }
}
