//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ejercicio_Prueba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class parroquia
    {
        public int idparroquia { get; set; }
        public string par_nombre { get; set; }
        public int ciudad_idciudad { get; set; }
    
        public virtual ciudad ciudad { get; set; }
    }
}
