//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ejercicio_Prueba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class provincia
    {
        public provincia()
        {
            this.ciudad = new HashSet<ciudad>();
        }
    
        public int idprovincia { get; set; }
        public string prov_nombre { get; set; }
    
        public virtual ICollection<ciudad> ciudad { get; set; }
    }
}
