//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutosDataAnnotation
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class auto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public auto()
        {
            this.compra = new HashSet<compra>();
        }
        [DisplayName("ID")]
        public int auto_id { get; set; }
        [Required(ErrorMessage = "{0} es un campo obligatorio")]
        [DisplayName("PLACA")]
        [MaxLength(8)]
        [RegularExpression(@"^([A-Z]{3})[-]([0-9]{4})$", ErrorMessage = "La placa debe tener 3 letras mayusculas y 4 digitos. Ejem:XBX-0458 ")]
        public string auto_placa { get; set; }
        [Required(ErrorMessage = "{0} es un campo obligatorio")]
        [Range(0.01, 1000.00, ErrorMessage = "Precio debe estar entre {1} y {2}")]
        [RegularExpression(@"^\$?\d+(\.(\d{2}))?$", ErrorMessage = "Valor debe tener dos decimales")]
        [DisplayName("VALOR")]
        public Nullable<float> auto_valor { get; set; }
        [DisplayName("COMPRA")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<compra> compra { get; set; }
    }
}
