//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutosDataAnnotation
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class compra
    {
        [DisplayName("ID")]
        public int com_id { get; set; }
        [Required(ErrorMessage = "{0} es un campo obligatorio")]
        [Range(typeof(DateTime), "01/01/1900", "05/11/2018",
        ErrorMessage = "fechas aceptadas para campo {0} entre {1} y {2}")]
        [DisplayName("FECHA")]
        public Nullable<System.DateTime> com_fecha { get; set; }
        [Required(ErrorMessage = "{0} es un campo obligatorio")]
        [Range(0.01, 1000.00, ErrorMessage = "Precio debe estar entre {1} y {2}")]
        [RegularExpression(@"^\$?\d+(\.(\d{2}))?$", ErrorMessage = "Valor debe tener dos decimales")]
        [DisplayName("SUBTOTAL")]
        public Nullable<float> con_subtotal { get; set; }
        [DisplayName("IVA")]
        public Nullable<float> con_iva { get; set; }
        [DisplayName("TOTAL")]
        public Nullable<float> con_total { get; set; }
        public int auto_auto_id { get; set; }
        public int cliente_cli_id { get; set; }
    
        public virtual auto auto { get; set; }
        public virtual cliente cliente { get; set; }
    }
}
